version: "3"
services:
  apache-demo:
    image: httpd
    container_name: apache-demo
    ports:
      - "80:80"
      - "81:81"
      - "10080:10080"
    volumes:
      - ${PWD}/conf/my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ${PWD}/html/public-html/:/usr/local/apache2/htdocs/
      - ${PWD}/html/home/doc/:/home/doc/
      - ${PWD}/logs/:/usr/local/apache2/logs/

  my-tomcat-1:
    image: tomcat:9.0
    container_name: my-tomcat-1
    ports:
      - "8888:8080"
    volumes:
      - ${PWD}/tomcat/webapps/:/usr/local/tomcat/webapps/

  my-tomcat-2:
    image: tomcat:9.0
    container_name: my-tomcat-2
    ports:
      - "8889:8080"
    volumes:
      - ${PWD}/tomcat/webapps/:/usr/local/tomcat/webapps/